package com.ui;

import com.dao.TaiXeDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.entity.TaiXe;
import com.utils.MsgBox;
import com.utils.Auth;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
public class QuanLyTaiXeForm extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVienForm
     */
    public QuanLyTaiXeForm() {
        initComponents();
        DefaultTableCellRenderer headerCellRenderer = new DefaultTableCellRenderer();
        headerCellRenderer.setBackground(new Color(192,227,149));
        for(int i = 0; i < tblTaiXe.getModel().getColumnCount(); ++i)
        {
            tblTaiXe.getColumnModel().getColumn(i).setHeaderRenderer(headerCellRenderer);
        }
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupVaiTro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblMaTX = new javax.swing.JLabel();
        txtMaTX = new javax.swing.JTextField();
        lblTenTX = new javax.swing.JLabel();
        txtTenTX = new javax.swing.JTextField();
        lblTinhTrang = new javax.swing.JLabel();
        rdoKhongHoatDong = new javax.swing.JRadioButton();
        rdoDangHoatDong = new javax.swing.JRadioButton();
        lblDiaChi = new javax.swing.JLabel();
        panelBorderForGioiThieuForm1 = new com.ui.PanelBorderForGioiThieuForm();
        jLabel2 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTaiXe = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 250, 254));

        jLabel1.setBackground(new java.awt.Color(248, 250, 254));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 227, 149));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ TÀI XẾ");

        lblMaTX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMaTX.setText("Mã tài xế :");

        lblTenTX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTenTX.setText("Tên tài xế:");

        txtTenTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTXActionPerformed(evt);
            }
        });

        lblTinhTrang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTinhTrang.setText("Tình trạng hoạt động :");

        btngroupVaiTro.add(rdoKhongHoatDong);
        rdoKhongHoatDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoKhongHoatDong.setText("Không hoạt động");
        rdoKhongHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhongHoatDongActionPerformed(evt);
            }
        });

        btngroupVaiTro.add(rdoDangHoatDong);
        rdoDangHoatDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoDangHoatDong.setText("Đang hoạt động");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiaChi.setText("Địa chỉ :");

        panelBorderForGioiThieuForm1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ngoisao.png"))); // NOI18N

        javax.swing.GroupLayout panelBorderForGioiThieuForm1Layout = new javax.swing.GroupLayout(panelBorderForGioiThieuForm1);
        panelBorderForGioiThieuForm1.setLayout(panelBorderForGioiThieuForm1Layout);
        panelBorderForGioiThieuForm1Layout.setHorizontalGroup(
            panelBorderForGioiThieuForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderForGioiThieuForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorderForGioiThieuForm1Layout.setVerticalGroup(
            panelBorderForGioiThieuForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderForGioiThieuForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblTaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài xế", "Họ và tên", "Tình trạng hoạt động", "Địa chỉ", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTaiXe.setSelectionBackground(new java.awt.Color(35, 166, 97));
        tblTaiXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTaiXe);

        jPanel1.setBackground(new java.awt.Color(248, 250, 254));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setPreferredSize(new java.awt.Dimension(260, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(251, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(251, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        btnMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.setPreferredSize(new java.awt.Dimension(260, 35));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoi);

        jPanel2.setBackground(new java.awt.Color(248, 250, 254));

        btnFirst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/first.png"))); // NOI18N
        btnFirst.setPreferredSize(new java.awt.Dimension(260, 35));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirst);

        btnPre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        btnPre.setPreferredSize(new java.awt.Dimension(251, 35));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel2.add(btnPre);

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnNext.setPreferredSize(new java.awt.Dimension(251, 35));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext);

        btnLast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/last.png"))); // NOI18N
        btnLast.setPreferredSize(new java.awt.Dimension(260, 35));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel2.add(btnLast);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTenTX, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(lblMaTX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaTX)
                            .addComponent(txtTenTX)
                            .addComponent(txtDiaChi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoKhongHoatDong)
                                .addGap(18, 18, 18)
                                .addComponent(rdoDangHoatDong)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addComponent(panelBorderForGioiThieuForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaTX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenTX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoKhongHoatDong)
                            .addComponent(rdoDangHoatDong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelBorderForGioiThieuForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    int row  = -1;
    TaiXeDAO txdao = new TaiXeDAO();
    
    void init(){
        // design giao diện
        // textfield MaTX
        txtMaTX.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtMaTX.setBackground(new Color(235,235,235)); // background
        txtMaTX.setForeground(Color.decode("#7A8C8D"));
        txtMaTX.setFont(new java.awt.Font("sansserif", 0, 13));
        txtMaTX.setSelectionColor(new Color(75, 175, 152));
        // textfield TenTX
        txtTenTX.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtTenTX.setBackground(new Color(235,235,235)); // background
        txtTenTX.setForeground(Color.decode("#7A8C8D"));
        txtTenTX.setFont(new java.awt.Font("sansserif", 0, 13));
        txtTenTX.setSelectionColor(new Color(75, 175, 152));
        // combo TenMien
        txtDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtDiaChi.setBackground(new Color(235,235,235)); // background
        txtDiaChi.setForeground(Color.decode("#7A8C8D"));
        txtDiaChi.setFont(new java.awt.Font("sansserif", 0, 13));
        txtDiaChi.setSelectionColor(new Color(75, 175, 152));

        this.fillTable();
        this.updateStatus();
        this.row = -1;
    }
    
    void fillTable() { // Fill data to tblTaiXe
        DefaultTableModel model = (DefaultTableModel) tblTaiXe.getModel();
        model.setRowCount(0);
        try {
            List<TaiXe> list = txdao.selectAll();
            for (TaiXe nv : list) {
                Object[] row = {nv.getMaTX(), nv.getHoTen(),nv.getTrangThai() ? "Không hoạt động" : "Hoạt động", nv.getDiaChi(), nv.getHinh()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
        }
    }
    
    void setForm(TaiXe tx) { // Dsiplay TaiXe to form 
        try {
            txtMaTX.setText(tx.getMaTX());
            txtTenTX.setText(tx.getHoTen());
            if (tx.getTrangThai()) {
                rdoKhongHoatDong.setSelected(tx.getTrangThai());
            }
            rdoDangHoatDong.setSelected(!tx.getTrangThai());
            txtDiaChi.setText(tx.getDiaChi());
        } catch (Exception e) {
            
        }
    }

    TaiXe getForm() { // Create new TaiXe from form
        TaiXe tx = new TaiXe();
        tx.setMaTX(txtMaTX.getText());
        tx.setHoTen(txtTenTX.getText());
        tx.setTrangThai(rdoKhongHoatDong.isSelected());
        tx.setDiaChi(txtDiaChi.getText());
        return tx;
    }

    void clearForm() { // [btnMoi]
        TaiXe nv = new TaiXe();
        this.setForm(nv);
        this.row = -1;
        this.updateStatus();
    }

    void updateStatus() { // Change status of btns
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblTaiXe.getRowCount() - 1);
        // status form
        txtMaTX.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        // status backward and forward btn
//        btnFirst.setEnabled(edit && !first);
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnLast.setEnabled(edit && !last);
    }

    void insert() { // [btnThem]
        TaiXe tx = getForm();
        try {
            txdao.insert(tx);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Them moi thanh cong");
        } catch (Exception e) {
            MsgBox.alert(this, "Them moi that bai");
            e.printStackTrace();
        }

    }

    void update() { // [btnSua]
        TaiXe tx = getForm();
        try {
            txdao.update(tx);
            this.fillTable();
            MsgBox.alert(this, "Cap nhat thanh cong");
        } catch (Exception e) {
            MsgBox.alert(this, "Cap nhat that bai");
            e.printStackTrace();
        }
    }

    void delete() { // [btnXoa]
        String manv = txtMaTX.getText();
        if (manv.equals(Auth.user.getMaNV())) {
            MsgBox.alert(this, "Ban khong the xoa chinh ban!");
        } else if (MsgBox.confirm(this, "Ban thuc su muon xoa nhan vien nay?")) {
            try {
                txdao.delete(manv);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xoa thanh cong");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoa that bai");
                e.printStackTrace();
            }
        }
    }

    void edit() { // [tblTaiXe double click]
        String manv = (String) tblTaiXe.getValueAt(this.row, 0);
        TaiXe nv = txdao.selectById(manv);
        this.setForm(nv);
        this.updateStatus();
    }
    
    private void first(){
        this.row = 0;
        this.edit();
    } // btnFirst
    
    private void prev(){
        if(this.row > 0){
            this.row--;
            this.edit();
        }
    } // btnPrev
    
    private void next(){
        if(this.row < tblTaiXe.getRowCount() - 1){
            this.row++;
            this.edit();
        }
    } // btnNext
    
    private void last(){
        this.row = tblTaiXe.getRowCount() - 1;
        this.edit();
    } // btnLast
    private void txtTenTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTXActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void rdoKhongHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhongHoatDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoKhongHoatDongActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblTaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiXeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblTaiXe.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblTaiXeMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup btngroupVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblMaTX;
    private javax.swing.JLabel lblTenTX;
    private javax.swing.JLabel lblTinhTrang;
    private com.ui.PanelBorderForGioiThieuForm panelBorderForGioiThieuForm1;
    private javax.swing.JRadioButton rdoDangHoatDong;
    private javax.swing.JRadioButton rdoKhongHoatDong;
    private javax.swing.JTable tblTaiXe;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaTX;
    private javax.swing.JTextField txtTenTX;
    // End of variables declaration//GEN-END:variables
}
