package com.ui;

import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

public class QuanLyTuyenDuongForm extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyTuyenDuongForm
     */
    public QuanLyTuyenDuongForm() {
        initComponents();
        DefaultTableCellRenderer headerCellRenderer = new DefaultTableCellRenderer();
        headerCellRenderer.setBackground(new Color(192,227,149));
        for(int i = 0; i < tblTuyenDuong.getModel().getColumnCount(); ++i)
        {
            tblTuyenDuong.getColumnModel().getColumn(i).setHeaderRenderer(headerCellRenderer);
        }
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMaTuyenDuong = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        txtMaTuyenDuong = new javax.swing.JTextField();
        lblTenTuyenDuong = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtTenTuyenDuong = new javax.swing.JTextField();
        lblTenMien = new javax.swing.JLabel();
        cboTenMien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTuyenDuong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnTaoMoiLichTrinh = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(248, 250, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 227, 149));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ TUYẾN ĐƯỜNG");

        lblMaTuyenDuong.setText("Mã tuyến đường:");

        lblGia.setText("Giá:");

        lblTenTuyenDuong.setText("Tên tuyến đường:");

        lblTenMien.setText("Tên miền:");

        tblTuyenDuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tuyến đường", "Tên tuyến đường", "Giá", "Tên miền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTuyenDuong);

        jPanel2.setBackground(new java.awt.Color(248, 250, 254));

        btnThemMoi.setBackground(new java.awt.Color(192, 227, 149));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel2.add(btnThemMoi);

        btnSua.setBackground(new java.awt.Color(192, 227, 149));
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel2.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(192, 227, 149));
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel2.add(btnXoa);

        btnMoi.setBackground(new java.awt.Color(192, 227, 149));
        btnMoi.setText("Mới");
        btnMoi.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel2.add(btnMoi);

        btnTaoMoiLichTrinh.setBackground(new java.awt.Color(192, 227, 149));
        btnTaoMoiLichTrinh.setText("Tạo mới lịch trình");
        btnTaoMoiLichTrinh.setPreferredSize(new java.awt.Dimension(260, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaTuyenDuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenTuyenDuong, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaTuyenDuong, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(txtTenTuyenDuong))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenMien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGia)
                            .addComponent(cboTenMien, 0, 413, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaoMoiLichTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenMien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTenMien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoMoiLichTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoMoiLichTrinh;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTenMien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblMaTuyenDuong;
    private javax.swing.JLabel lblTenMien;
    private javax.swing.JLabel lblTenTuyenDuong;
    private javax.swing.JTable tblTuyenDuong;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaTuyenDuong;
    private javax.swing.JTextField txtTenTuyenDuong;
    // End of variables declaration//GEN-END:variables
    private void init(){
        // design giao diện
        // textfield MaTuyenDuong
        txtMaTuyenDuong.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtMaTuyenDuong.setBackground(new Color(235,235,235)); // background
        txtMaTuyenDuong.setForeground(Color.decode("#7A8C8D"));
        txtMaTuyenDuong.setFont(new java.awt.Font("sansserif", 0, 13));
        txtMaTuyenDuong.setSelectionColor(new Color(75, 175, 152));
        // textfield TenTuyenDuong
        txtTenTuyenDuong.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtTenTuyenDuong.setBackground(new Color(235,235,235)); // background
        txtTenTuyenDuong.setForeground(Color.decode("#7A8C8D"));
        txtTenTuyenDuong.setFont(new java.awt.Font("sansserif", 0, 13));
        txtTenTuyenDuong.setSelectionColor(new Color(75, 175, 152));
        // textfield Giá
        txtGia.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtGia.setBackground(new Color(235,235,235)); // background
        txtGia.setForeground(Color.decode("#7A8C8D"));
        txtGia.setFont(new java.awt.Font("sansserif", 0, 13));
        txtGia.setSelectionColor(new Color(75, 175, 152));
        // combo TenMien
        cboTenMien.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        cboTenMien.setBackground(new Color(235,235,235)); // background
        cboTenMien.setForeground(Color.decode("#7A8C8D"));
        cboTenMien.setFont(new java.awt.Font("sansserif", 0, 13));
    }
}
